#!/bin/bash
set -eo pipefail

REMOTE_HOST="${REMOTE_HOST:-evan@demschooltools.com}"
REMOTE_DIR="${REMOTE_DIR:-/home/evan}"

cleanup() {
    echo "Build/Deploy failed at line $1"
    exit 1
}
trap 'cleanup $LINENO' ERR

# Make sure that there are no uncommitted changes
git diff-index --quiet HEAD --

### Play Framework stuff
npm install
./sbt.sh clean dist
rsync -v -h --progress target/universal/demschooltools-1.1.zip "$REMOTE_HOST:$REMOTE_DIR/"


## React & Django stuff
(cd react && npm install && npm run build)

# -r is necessary here because ls-tree includes some symbolic link directories
# and we want to include the files that are contained in them.
git ls-tree -r --name-only head django | xargs zip -r django

# These files are generated by vite's build process and not in git
zip -r django django/static-vite/

rsync -v -h --progress django.zip "$REMOTE_HOST:$REMOTE_DIR/"

rm django.zip

echo "Build and copy successful. Files delivered to $REMOTE_HOST:$REMOTE_DIR"

echo "---"
echo "Next steps (SSH into the server):"
echo ""
echo "  # 1. Deploy Django"
echo "  ssh $REMOTE_HOST"
echo "  unzip -o django.zip -d /www/demschooltools/"
echo "  cd /www/demschooltools/django"
echo "  source ../set_env.sh"
echo "  uv run manage.py migrate --noinput"
echo "  uv run manage.py collectstatic --noinput"
echo "  ./run_django.sh  # gracefully restarts gunicorn"
echo ""
echo "  # 2. Verify health"
echo "  curl -f http://localhost:8000/health/ && echo 'Django OK'"
echo ""
echo "  # 3. Deploy Play (if needed)"
echo "  unzip -o demschooltools-1.1.zip -d /www/demschooltools/"
echo "  ./run_play.sh"
